#!/bin/bash

get_push_upstream() {
  local PREFIX="git push --set-upstream origin "
  local CUR_BRANCH="$(python3 $HOME/.config/zsh/fzf/git/get_cur_branch.py)"
  local CMD="${PREFIX}${CUR_BRANCH}"
  eval ${CMD}
}

get_push_upstream
