return {
  -- {
  --   function ()
  --     local blink = require("lazyvim.plugins.extras.coding.blink")
  --
  --   end
  --   opts = {
  --     snippets = {
  --       expand = function(snippet, _)
  --         return LazyVim.cmp.expand(snippet)
  --       end,
  --     },
  --
  --     completion = {
  --       accept = {
  --         auto_brackets = {
  --           enabled = false,
  --         },
  --       },
  --
  --       documentation = {
  --         auto_show = true,
  --         auto_show_delay_ms = 200,
  --       },
  --
  --       ghost_text = {
  --         enabled = vim.g.ai_cmp,
  --       },
  --     },
  --   },
  -- },
}
